baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'default'

summaryLength = 10

[Params]
  custom_css = "css/output.css"
  profile_picture = "images/profile-picture.png"
  keywords = ["default_key_1", "default_key_2"]
  description = "This is the default description of the website."

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
    [[menu.nav]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.nav]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

    [[menu.nav]]
    identifier = "open-source"
    name = "Open Source"
    url = "/open-source/"
    weight = 3